Name: build-openlane-sky130
on: [push]

jobs:
  build-uart:
    runs-on: ubuntu-latest
    env:
      REPO : uart
      VLNV : secworks:util:uart
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: uart
      - run: echo "EDALIZE_LAUNCHER=el_docker" >> $GITHUB_ENV
      - run: pip3 install fusesoc
      - run: fusesoc library add $REPO $GITHUB_WORKSPACE/$REPO
      - run: fusesoc run --target=sky130 $VLNV

  sim-icarus:
    runs-on: ubuntu-latest
    env:
      REPO : uart
      VLNV : secworks:util:uart
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: uart
      - run: sudo apt install iverilog
      - run: pip3 install fusesoc
      - run: fusesoc library add $REPO $GITHUB_WORKSPACE/$REPO
      - run: fusesoc run --target=tb_uart $VLNV

  lint-verilator:
    runs-on: ubuntu-latest
    env:
      REPO : uart
      VLNV : secworks:util:uart
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: uart
      - run: sudo apt install verilator
      - run: pip3 install fusesoc
      - run: fusesoc library add $REPO $GITHUB_WORKSPACE/$REPO
      - run: fusesoc run --target=lint $VLNV
